### PR TITLE
Add and update documentation for RobotFramework AIO tutorial

### PR DESCRIPTION
**Pull request by namsonx**

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Documentation rst files placed in several doc_src folders. To have a better separation between these source files and the files the users work with it would be better to place them in only one doc_src folder.

The '900_Building_testsuites' folder contain subfolders only. It would be more helpful to have already at this level a document available describing in general how to build testsuites (an introduction; something like 100_variables_and_datatypes\variables_and_datatypes.html).

**Comment by namsonx** [comment]
> Documentation rst files placed in several doc_src folders. To have a better separation between these source files and the files the users work with it would be better to place them in only one doc_src folder.
> 

Hello @HolQue ,

    Thank you for your feedback!
    I will place all .rst files into 1 doc_src folder at the sub-folder of '900_Building_testsuites'. I also create an introduction for folder '900_Building_testsuites' as well.

Thank you, 
Son

**Comment by test-fullautomation** [comment]
Hi Son,
thank you for your pull request!
It looks already promising.

Please use as reference the TML chapter "how to build test suites". 
Goal should be to explain a user how to setup a new test suite inclusive variant/project switching.
The TML chapter defines for this ComponentA, ComponentB, ... where the code inside is executed dependent on the variant.
The generated documentation explains for each file what the tml content is doing.
Also described are the runlevels as I remember. You should have 2 everywhere, but sombody should understand why.
Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hi Son, thank you for your pull request! It looks already promising.
> 
> Please use as reference the TML chapter "how to build test suites". Goal should be to explain a user how to setup a new test suite inclusive variant/project switching. The TML chapter defines for this ComponentA, ComponentB, ... where the code inside is executed dependent on the variant. The generated documentation explains for each file what the tml content is doing. Also described are the runlevels as I remember. You should have 2 everywhere, but sombody should understand why. Thank you, Thomas

**Pull request closed without merging**
